# docker-compose.yml
services:
  postgres:
    image: ankane/pgvector
    container_name: thesis_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=thesisdb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  chroma:
    image: chromadb/chroma
    container_name: thesis_chroma
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma

  web_scraper:
    build: ./web_scraper
    container_name: thesis_scraper
    restart: unless-stopped
    ports:
      - "8003:8003"

  agent_app:
    build: .
    container_name: thesis_agents
    restart: unless-stopped
    depends_on:
      - postgres
      - chroma
      - web_scraper
    ports:
      - "8001:8001"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/thesisdb
      - CHROMA_HOST=chroma
      - CHROMA_PORT=8000
    volumes:
      - ./src:/app/src
      - ./run.py:/app/run.py
      - ./data:/app/data
      - ./test:/app/test

  frontend:
    build: ./frontend
    container_name: thesis_frontend
    restart: unless-stopped
    ports:
      - "8501:8501"
    depends_on:
      - agent_app

volumes:
  pg_data:
  chroma_data: