# docker-compose.yml
version: '3.8'

services:
  # The Database for Structured Data (Financials, Sentiment Scores)
  postgres_db:
    image: ankane/pgvector
    container_name: thesis_postgres
    environment:
      POSTGRES_DB: thesisdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # The Vector Database for RAG (Reviews, Scraped Content)
  chroma_db:
    image: chromadb/chroma
    container_name: thesis_chroma
    ports:
      - "8001:8000"

  # The Central Multi-Agent Application
  multi_agent_app:
    build: ./multi_agent_app
    container_name: thesis_agents
    depends_on:
      - postgres_db
      - chroma_db
    ports:
      - "8002:8000"
    volumes:
      # Mount the downloaded model folder into the container
      - ./Meta-Llama-3-8B-Instruct:/models/llama3-8b
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - DATABASE_URL=postgresql://user:password@postgres_db:5432/thesisdb
      - CHROMA_HOST=chroma_db
      - CHROMA_PORT=8000

volumes:
  pg_data:
